### PR TITLE
Added Progressive web app and snackbar

### PR DESCRIPTION
**Pull request by rajat-0206**
I have created a progressive web app for this project. This mean that it can be installed on phone as a APK file. I am providing the apk with this commit. I have also added snackbar on ADD and DELETE. Now a snackbar comes from bottom when a item is added or deleted.
The APK file is present in the commit by the name - TODO_base.apk 
It can also be downloaded from here => https://drive.google.com/file/d/1NBC6mVUD6xfPutymOtq1ZDq5I2kR47O6/view?usp=sharing

### CODE REVIEW

**Comment by chaudhary19** [comment]
hi, Rajat. 
Thanks for adding this feature, but can you please look at the conflicts it is showing, because someone has added the theme feature, that's why your file is showing the conflict. Kindly make proper changes so that I can merge it. Thanks :)

**Comment by rajat-0206** [comment]
Hey Mayank I have resolved all the conflict. Kindly merge this change before you merge any other as then conflict will come again.

**Review by rajat-0206 — COMMENTED** [review]
I have corrected dark theme

**Review by chaudhary19 — APPROVED** [review]
Approved

**Pull request merged**
