### PR TITLE
Contact Form

### PR DESCRIPTION
**Pull request by arsalanhub**
Added contact tab in navigation bar in index.html & then added contact form for the website. Also fixed href issue of navigation bar.

### CODE REVIEW

**Comment by chaudhary19** [comment]
kindly check this with the newer version, then I will merge it :)

**Comment by arsalanhub** [comment]
Yes updated with newer version.

**Comment by chaudhary19** [comment]
someone has added a theme option, so please make appropriate changes so that I can merge it :)

**Comment by manav014** [comment]
Well!! Thank you for this PR, please fill the merged PR form.

**Pull request merged**
